services:
  # Alexandria STX Data Lake background worker
  - type: worker
    name: alexandria-data-lake-svc
    env: node
    region: oregon
    plan: starter
    buildCommand: yarn && yarn build
    startCommand: yarn start:prod
    autoDeploy: false
    envVars:
      - key: STREAM_HISTORICAL_DATA
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: alexandria-data-lake-db
          property: connectionString
      - key: NODE_VERSION
        value: 16.15.1

  # Alexandria STX Indexer background worker
  - type: worker
    name: alexandria-indexer-svc
    env: node
    region: oregon
    plan: starter
    buildCommand: yarn && yarn build
    startCommand: yarn start:prod
    autoDeploy: false
    envVars:
      - key: CHAIN_SYMBOL
        value: Stacks
      - key: ENABLE_STREAMER_SUBSCRIPTION
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: alexandria-indexer-db
          property: connectionString
      - key: STACKS_STREAMER_SQL_DATABASE_URL
        fromDatabase:
          name: alexandria-data-lake-db
          property: connectionString
      - key: RUN_SEED
        value: true
      - key: NODE_VERSION
        value: 16.15.1
      - key: LOG_LEVEL
        value: debug

databases:
  # Alexandria STX Data Lake database
  - name: alexandria-data-lake-db
    plan: free
    ipAllowList: []

  # Alexandria STX Indexer database
  - name: alexandria-indexer-db
    plan: starter
    ipAllowList: []
