services:
  - type: web
    name: alexandria-indexer-svc
    env: node
    region: oregon
    plan: free
    buildCommand: yarn; yarn build
    startCommand: yarn start:prod
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alexandria-index-db
          property: connectionString
      - key: STACKS_STREAMER_SQL_DATABASE_URL
        fromDatabase:
          name: alexandria-data-lake-db
          property: connectionString
      - key: RUN_SEED
        value: true
      - key: NODE_VERSION
        value: 16.15.1

databases:
  - name: alexandria-index-db
    plan: free
    ipAllowList: []
  - name: alexandria-data-lake-db
    plan: free
    ipAllowList: []
