-- AlterTable
ALTER TABLE "nft_state" ALTER COLUMN "mint_tx" DROP NOT NULL,
ALTER COLUMN "list_price" DROP NOT NULL,
ALTER COLUMN "list_seller" DROP NOT NULL,
ALTER COLUMN "list_block_height" DROP NOT NULL,
ALTER COLUMN "list_tx_index" DROP NOT NULL,
ALTER COLUMN "asking_price" DROP NOT NULL,
ALTER COLUMN "asking_block_height" DROP NOT NULL,
ALTER COLUMN "asking_tx_index" DROP NOT NULL,
ALTER COLUMN "asking_seller" DROP NOT NULL,
ALTER COLUMN "bid_price" DROP NOT NULL,
ALTER COLUMN "bid_buyer" DROP NOT NULL,
ALTER COLUMN "bid_contract" DROP NOT NULL,
ALTER COLUMN "bid_block_height" DROP NOT NULL,
ALTER COLUMN "bid_tx_index" DROP NOT NULL,
ALTER COLUMN "staking_contract" DROP NOT NULL,
ALTER COLUMN "staked_owner" DROP NOT NULL,
ALTER COLUMN "staked_block_height" DROP NOT NULL,
ALTER COLUMN "staked_tx_index" DROP NOT NULL;
